namespace BarberBooking.Domain.Entities;

public class SystemAlert : BaseEntity
{
    public string Title { get; set; } = string.Empty;
    public string Message { get; set; } = string.Empty;
    public string Severity { get; set; } = "Info";
    public string Category { get; set; } = "Custom";
    public string Status { get; set; } = "New";
    public string Priority { get; set; } = "Medium";
    public string Source { get; set; } = "System";
    public bool IsAutoGenerated { get; set; }
    public DateTime? ReadAt { get; set; }
    public string? CreatedBy { get; set; }
    public string? RelatedEntityType { get; set; }
    public Guid? RelatedEntityId { get; set; }
    public Guid? TargetUserId { get; set; }
    public string? TargetUserType { get; set; }
    public User? TargetUser { get; set; }
}
