using BarberBooking.Domain.Entities;
using BarberBooking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace BarberBooking.API.Services;

public interface IAutoAlertService
{
    Task CreateAlertAsync(string title, string message, string severity, string category, string source, string priority = "Medium", Guid? targetUserId = null, string? targetType = null, string? relatedEntityType = null, Guid? relatedEntityId = null, string? createdBy = null);
    Task CheckSubscriptionExpirationsAsync();
    Task CheckBookingLimitsAsync();
}

public class AutoAlertService : BackgroundService, IAutoAlertService
{
    private readonly IServiceProvider _serviceProvider;
    private readonly TimeSpan _checkInterval = TimeSpan.FromHours(6);

    public AutoAlertService(IServiceProvider serviceProvider)
    {
        _serviceProvider = serviceProvider;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                await CheckSubscriptionExpirationsAsync();
                await CheckBookingLimitsAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[AutoAlertService] Error: {ex.Message}");
            }

            await Task.Delay(_checkInterval, stoppingToken);
        }
    }

    public async Task CreateAlertAsync(string title, string message, string severity, string category, string source, string priority = "Medium", Guid? targetUserId = null, string? targetType = null, string? relatedEntityType = null, Guid? relatedEntityId = null, string? createdBy = null)
    {
        using var scope = _serviceProvider.CreateScope();
        var context = scope.ServiceProvider.GetRequiredService<BarberBookingDbContext>();

        var alert = new SystemAlert
        {
            Title = title,
            Message = message,
            Severity = severity,
            Category = category,
            Status = "New",
            Priority = priority,
            Source = source,
            IsAutoGenerated = source == "System" || source == "BackgroundJob",
            TargetUserId = targetUserId,
            TargetUserType = targetType,
            RelatedEntityType = relatedEntityType,
            RelatedEntityId = relatedEntityId,
            CreatedBy = createdBy ?? "System"
        };

        context.SystemAlerts.Add(alert);
        await context.SaveChangesAsync();
    }

    public async Task CheckSubscriptionExpirationsAsync()
    {
        using var scope = _serviceProvider.CreateScope();
        var context = scope.ServiceProvider.GetRequiredService<BarberBookingDbContext>();

        var expiringSoon = await context.BarberSubscriptions
            .Where(s => s.Status == "active" && s.EndDate > DateTime.UtcNow && s.EndDate <= DateTime.UtcNow.AddDays(7))
            .Include(s => s.BarberProfile)
            .ThenInclude(bp => bp.User)
            .ToListAsync();

        foreach (var sub in expiringSoon)
        {
            var daysRemaining = (sub.EndDate - DateTime.UtcNow).Days;
            var existingAlert = await context.SystemAlerts
                .AnyAsync(a => a.RelatedEntityType == "BarberSubscription"
                    && a.RelatedEntityId == sub.Id
                    && a.Status != "Resolved"
                    && a.CreatedAt > DateTime.UtcNow.AddDays(-1));

            if (existingAlert) continue;

            var severity = daysRemaining <= 3 ? "Critical" : "Warning";
            var priority = daysRemaining <= 3 ? "Critical" : "High";
            var userName = sub.BarberProfile?.User?.FullName ?? "حلاق";

            await CreateAlertAsync(
                title: $"اشتراك {userName} ينتهي خلال {daysRemaining} أيام",
                message: $"اشتراك الخطة {sub.BarberProfile?.SubscriptionPlan} للحلاق {userName} ينتهي بتاريخ {sub.EndDate:yyyy-MM-dd}. المتبقي {daysRemaining} يوم.",
                severity: severity,
                category: "Subscription",
                source: "BackgroundJob",
                priority: priority,
                targetUserId: sub.BarberProfile?.UserId,
                targetType: "Barber",
                relatedEntityType: "BarberSubscription",
                relatedEntityId: sub.Id
            );
        }
    }

    public async Task CheckBookingLimitsAsync()
    {
        using var scope = _serviceProvider.CreateScope();
        var context = scope.ServiceProvider.GetRequiredService<BarberBookingDbContext>();

        var activeSubs = await context.BarberSubscriptions
            .Where(s => s.Status == "active" && s.EndDate > DateTime.UtcNow)
            .Include(s => s.SubscriptionPlan)
            .Include(s => s.BarberProfile)
            .ThenInclude(bp => bp.User)
            .ToListAsync();

        foreach (var sub in activeSubs)
        {
            if (sub.SubscriptionPlan == null) continue;

            var currentMonth = DateTime.UtcNow.Month;
            var currentYear = DateTime.UtcNow.Year;
            var monthlyBookings = await context.Bookings
                .CountAsync(b => b.BarberProfileId == sub.BarberProfileId
                    && b.CreatedAt.Month == currentMonth
                    && b.CreatedAt.Year == currentYear
                    && b.Status != "Cancelled"
                    && b.Status != "Rejected");

            var limit = sub.SubscriptionPlan.MaxBookingsPerMonth;
            if (limit <= 0) continue;

            var usagePercent = (double)monthlyBookings / limit * 100;

            if (usagePercent >= 100)
            {
                var existingAlert = await context.SystemAlerts
                    .AnyAsync(a => a.RelatedEntityType == "BarberProfile"
                        && a.RelatedEntityId == sub.BarberProfileId
                        && a.Category == "Booking"
                        && a.Status != "Resolved"
                        && a.CreatedAt.Month == currentMonth
                        && a.CreatedAt.Year == currentYear);

                if (existingAlert) continue;

                var userName = sub.BarberProfile?.User?.FullName ?? "حلاق";
                await CreateAlertAsync(
                    title: $"الحلاق {userName} وصل لحد الحجوزات الأقصى",
                    message: $"الحلاق {userName} استخدم {monthlyBookings}/{limit} حجز هذا الشهر. الخطة: {sub.SubscriptionPlan.Name}.",
                    severity: "Warning",
                    category: "Booking",
                    source: "BackgroundJob",
                    priority: "High",
                    targetUserId: sub.BarberProfile?.UserId,
                    targetType: "Barber",
                    relatedEntityType: "BarberProfile",
                    relatedEntityId: sub.BarberProfileId
                );
            }
            else if (usagePercent >= 80)
            {
                var existingAlert = await context.SystemAlerts
                    .AnyAsync(a => a.RelatedEntityType == "BarberProfile"
                        && a.RelatedEntityId == sub.BarberProfileId
                        && a.Category == "Booking"
                        && a.Status != "Resolved"
                        && a.CreatedAt.Month == currentMonth
                        && a.CreatedAt.Year == currentYear
                        && a.Message.Contains("80%"));

                if (existingAlert) continue;

                var userName = sub.BarberProfile?.User?.FullName ?? "حلاق";
                await CreateAlertAsync(
                    title: $"تنبيه: الحلاق {userName} قرب من حد الحجوزات",
                    message: $"الحلاق {userName} استخدم {monthlyBookings}/{limit} حجز ({usagePercent:F0}%) هذا الشهر.",
                    severity: "Info",
                    category: "Booking",
                    source: "BackgroundJob",
                    priority: "Medium",
                    targetUserId: sub.BarberProfile?.UserId,
                    targetType: "Barber",
                    relatedEntityType: "BarberProfile",
                    relatedEntityId: sub.BarberProfileId
                );
            }
        }
    }
}
